flask_app/main/routes.py
from flask import Flask, render_template, url_for, redirect, request, Blueprint
import requests
from bs4 import BeautifulSoup
from flask_login import login_user, current_user, logout_user, login_required
from flask_app.model import User, Review
from flask_app.forms import RegistrationForm, LoginForm, ReviewForm
from flask_app import db, bcrypt

dorms = []

main = Blueprint("main", __name__)

def removeEscapeSequences(word):
    word = word.replace('\t', '')
    word = word.replace('\n', '')
    return word

@main.route('/')
def index():
    global dorms
    response = requests.get('http://reslife.umd.edu/hallsatglance/')
    soup = BeautifulSoup(response.text, features="html.parser")

    lists = soup.find_all("td", {"width" : "62"})
    cutoff = lists[1:]

    dorms = list(map(lambda dorm: removeEscapeSequences(dorm), map(lambda dorm: dorm.get_text(), filter(lambda tag:tag.get_text()!="", cutoff))))

    if current_user.is_authenticated:
        return redirect('/home')

    registrationForm = RegistrationForm()
    loginForm = LoginForm()

    return render_template('main.html', dorms=dorms, loginForm=loginForm, registrationForm=registrationForm)

@main.route('/review/<dorm>', methods=["GET", "POST"])
def review(dorm):
    form = ReviewForm()
    if form.validate_on_submit():
        review = Review(dorm=dorm, amenities=int(form.amenities.data), location=int(form.location.data),
            social=int(form.social.data), comment=form.comments.data, author=current_user)
        db.session.add(review)
        db.session.commit()

        return redirect('/home')
    
    return render_template('review.html', dorm=dorm, form=form)

@main.route('/home')
def home():
    global dorms
    lst = []

    for dorm in dorms:
        reviews = Review.query.filter_by(dorm=dorm)
        count = 0
        for review in reviews:
            count += review.location + review.social + review.amenities
        lstReviews = list(reviews)
        if (len(lstReviews) == 0):
            average = 'N/A'
        else:
            average = round(count / (len(list(reviews)) * 3), 2)
        lst.append((dorm, average))

    return render_template('home.html', dorms=lst)

@main.route('/details/<dorm>')
def details(dorm):
    reviews = Review.query.filter_by(dorm=dorm)

    if (len(list(reviews)) != 0):
        averageSocial = 0
        averageLocation = 0
        averageAmenities = 0
        for review in reviews:
            averageSocial += review.amenities
            averageLocation += review.social
            averageAmenities += review.amenities
        
        averageSocial = round(averageSocial / len(list(reviews)), 2)
        averageLocation = round(averageLocation / len(list(reviews)), 2)
        averageAmenities = round(averageAmenities / len(list(reviews)), 2)
    else:
        averageSocial = 'N/A'
        averageLocation = 'N/A'
        averageAmenities = 'N/A'

    return render_template('details.html', dorm=dorm, social=averageSocial, 
        location=averageLocation, amenities=averageAmenities, reviews=reviews)

@main.route('/about')
def about():
    return render_template('about.html')

flask_app/users/routes.py
from flask import Flask, render_template, url_for, redirect, request, Blueprint, session
import requests
from bs4 import BeautifulSoup
from flask_login import login_user, current_user, logout_user, login_required
from flask_app.model import User
from flask_app.forms import RegistrationForm, LoginForm, UpdateForm
from flask_app import db, bcrypt

import qrcode
import qrcode.image.svg as svg

from io import BytesIO

dorms = []

users = Blueprint("users", __name__)

@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect('/home')

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()

        if user is not None and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            return redirect('/home')

    return render_template('login.html', title='Login', form=form)

@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect('/home')

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed = bcrypt.generate_password_hash(form.password.data).decode('utf-8')

        user = User(username=form.username.data, password=hashed)
        db.session.add(user)
        db.session.commit()

        # return redirect(url_for('users.login'))
        session['reg_username'] = user.username

        return redirect(url_for('users.tfa'))
    
    return render_template('register.html', title='Register', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect('/')

@users.route("/tfa")
def tfa():
    if 'reg_username' not in session:
        return redirect(url_for('main.index'))

    headers = {
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0' # Expire immediately, so browser has to reverify everytime
    }

    return render_template('tfa.html'), headers

@users.route("/qr_code")
def qr_code():
    if 'reg_username' not in session:
        return redirect(url_for('main.index'))
    
    user = User.query.filter_by(username=session['reg_username']).first()

    session.pop('reg_username')

    img = qrcode.make(user.get_auth_uri(), image_factory=svg.SvgPathImage)

    stream = BytesIO()

    img.save(stream)

    headers = {
        'Content-Type': 'image/svg+xml',
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0' # Expire immediately, so browser has to reverify everytime
    }

    return stream.getvalue(), headers

@users.route("/profile", methods=["GET", "POST"])
def profile():
    form = UpdateForm()

    if form.validate_on_submit():
        current_user.username = form.username.data

        db.session.commit()

        return redirect(url_for('users.profile'))
    
    elif request.method == 'GET':
        form.username.data = current_user.username
    
    return render_template('profile.html', title='Account', form=form)

flask_app/templates/about.html
{% extends "base.html" %}
{% block content %}
    <div id="navbar">
        <div id="site-title-container">
            <a style="flex-grow: 1" id="site-title" href="/home">Dorm-Reviewer</a>
        </div>

        <div id="site-pages-container">
            <a href="/about" class="nav-selector">About</a>
            <a href="/profile" class="nav-selector">Profile</a>
            <a href="/logout" class="nav-selector">Logout</a>
        </div>
    </div>

    <div class="card">
        <p class="description">
            This project is a crowdsourced review web app for UMD dorms. Users can leave
            reviews for any dorm on campus and rate them but their amenities, social atmosphere,
            and location. The main page shows each dorm with its average rating of the 3 across all
            of the reviews.
        </p>
    </div>
{% endblock %}

flask_app/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
    <title>Dorm-Reviewer</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

flask_app/templates/details.html
{% extends "base.html" %}
{% block content %}
    <div id="navbar">
        <div id="site-title-container">
            <a style="flex-grow: 1" id="site-title" href="/home">Dorm-Reviewer</a>
        </div>

        <div id="site-pages-container">
            <a href="/about" class="nav-selector">About</a>
            <a href="/profile" class="nav-selector">Profile</a>
            <a href="/logout" class="nav-selector">Logout</a>
        </div>
    </div>

    <div class="ratings-card">
        <h1>{{dorm}} Reviews</h1>

        <div class="review-rating-wrapper">
            <div class="average-rating-container">
                <span>Amenities</span>
                <span>{{amenities}}</span>
            </div>
            <div class="average-rating-container">
                <span>Social</span>
                <span>{{social}}</span>
            </div>
            <div class="average-rating-container">
                <span>Location</span>
                <span>{{location}}</span>
            </div>
        </div>
    </div>

    <div class="review-container">
        {% for review in reviews %}
        <div class="review">
            <div class="review-info-container">
                <span class="review-author">{{review.author.username}}</span>
                <div class="review-rating-wrapper">
                    <div class="review-rating-container">
                        <span>Social</span>
                        <span>{{review.social}}</span>
                    </div>
                    <div class="review-rating-container">
                        <span>Amenities</span>
                        <span>{{review.amenities}}</span>
                    </div>
                    <div class="review-rating-container">
                        <span>Location</span>
                        <span>{{review.location}}</span>
                    </div>
                </div>
            </div>
            <div class="comment-container">
                {{review.comment}}
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

flask_app/templates/home.html
{% extends "base.html" %}
{% block content %}
    <div id="navbar">
        <div id="site-title-container">
            <a style="flex-grow: 1" id="site-title" href="/home">Dorm-Reviewer</a>
        </div>

        <div id="site-pages-container">
            <a href="/about" class="nav-selector">About</a>
            <a href="/profile" class="nav-selector">Profile</a>
            <a href="/logout" class="nav-selector">Logout</a>
        </div>
    </div>

    <div id="card-wrapper">
        {% for dorm in dorms %}
            <div class="card">
                <div class="container">
                    <h1 id="card-header" style="text-align: center">{{dorm[0]}}</h1>
                    <h2 style="text-align: center"> {{dorm[1]}} </h2>
                    <div id="card-form">
                        <form class="button-form" action="/review/{{dorm[0]}}">
                            <button class="material-button">Leave a review</button>
                        </form>
                        <form class="button-form" action="/details/{{dorm[0]}}">
                            <button class="material-button">Details</button>
                        </form>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

flask_app/templates/login.html
{% extends "base.html" %}
{% block content %}
    <h1 id="main-title">Dorm Reviewer</h1>

    <div id="login-register-container">
        <div id="login-container"> 
            <div class="form">
                <form action="" method="post">
                    {{ form.csrf_token }}
                    <div>
                        {{ form.username.label(class="form-control-label green-text") }}
                        {{ form.username(class="form-control form-control-md") }}
                        {% if form.username.errors %}
                            <div>
                                {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                    <div>
                        {{ form.password.label(class="form-control-label green-text") }}
                        {{ form.password(class="form-control form-control-md") }}
                        {% if form.password.errors %}
                            <div>
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                    <div>
                        {{ form.submit (class="button") }}
                    </div>
                </form>
            </div>
        </div>        
    </div>
{% endblock %}

flask_app/templates/main.html
{% extends "base.html" %}
{% block content %}
    <h1 id="main-title">Dorm Reviewer</h1>
    <div class="main-button-container">
        <form class="button-form" action="/login">
            <button class="material-button-main">Login</button>
        </form>
        <form class="button-form" action="/register">
            <button class="material-button-main">Register</button>
        </form>
    </div>
{% endblock %}

flask_app/templates/profile.html
{% extends "base.html" %}
{% block content %}
    <div id="navbar">
        <div id="site-title-container">
            <a style="flex-grow: 1" id="site-title" href="/home">Dorm-Reviewer</a>
        </div>

        <div id="site-pages-container">
            <a href="/about" class="nav-selector">About</a>
            <a href="/profile" class="nav-selector">Profile</a>
            <a href="/logout" class="nav-selector">Logout</a>
        </div>
    </div>

    <div class="update-card">
        <div>
            <h2>{{ current_user.username }}</h2>
        </div>
        <form action="" method="post">
            {{ form.csrf_token }}
            <div class="update-container">
                {{ form.username.label }}
                {{ form.username }}
    
                {% if form.username.errors %}
                    <div>
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="update-container">
                {{ form.submit }}
            </div>
            {#
                Username, Password, and Confirm Password fields go here, from the UpdateForm, plus Bootstrap
                wk9 has examples of how to use Bootstrap.
                Plus, csrf token
            #}
        </form>
    </div>

   
{% endblock %}

flask_app/templates/register.html
{% extends "base.html" %}
{% block content %}
    <h1 id="main-title">Dorm Reviewer</h1>
        <div id="register-container">
            <div class="form">
                <form action="" method="post">
                        {{ form.csrf_token }}
                        <div>
                            {{ form.username.label(class="form-control-label green-text") }}
                            {{ form.username(class="form-control form-control-md") }}
                            {% if form.username.errors %}
                                <div>
                                    {% for error in form.username.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                        <div>
                            {{ form.password.label(class="form-control-label green-text") }}
                            {{ form.password(class="form-control form-control-md") }}
                            {% if form.password.errors %}
                                <div>
                                    {% for error in form.password.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                        <div>
                            {{ form.confirm_password.label(class="form-control-label green-text") }}
                            {{ form.confirm_password(class="form-control form-control-md") }}
                            {% if form.confirm_password.errors %}
                                <div>
                                    {% for error in form.confirm_password.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                        <div>
                            {{ form.submit(class="button") }}
                        </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

flask_app/templates/review.html
{% extends "base.html" %}
{% block content %}
    <div id="navbar">
        <div id="site-title-container">
            <a style="flex-grow: 1" id="site-title" href="/home">Dorm-Reviewer</a>
        </div>

        <div id="site-pages-container">
            <a href="/about" class="nav-selector">About</a>
            <a href="/profile" class="nav-selector">Profile</a>
            <a href="/logout" class="nav-selector">Logout</a>
        </div>
    </div>

    <h1>Rate {{dorm}}</h1>

    <div class="form">
        <form action="" method="post">
            {{ form.csrf_token }}
            <div>
                {{ form.amenities.label() }}
                {{ form.amenities(class="radio-container") }}
            </div>
            <div>
                {{ form.location.label() }}
                {{ form.location(class="radio-container") }}
            </div>
            <div>
                {{ form.social.label() }}
                {{ form.social(class="radio-container") }}
            </div>
            <div>
                {{ form.comments.label(class="form-control-label green-text") }}
                {{ form.comments(class="comments-form") }}
            </div>
            <div>
                {{ form.submit(class="button") }}
            </div>
        </form>
    </div>
{% endblock %}

flask_app/templates/tfa.html
{% extends "base.html" %}
{% block content %}
    <h1 id="main-title">Dorm Reviewer</h1>
    <div>
        <h2>Two-Factor Auth Enrollment</h2>
    </div>
    <div class="tfa">
        This website requires mandatory 2FA enrollment. 
    </div>
    <!-- Registration Form: -->
    <p class="tfa">
        Use a authenticator app to enroll with us! You will need to use this app to login in the future.
    </p>

    <div class="qr-container">
        <img src={{ url_for('users.qr_code') }} alt="QR Code for 2FA">
    </div>

    <div class="tfa">
        When you're done, you can go to the <a href={{ url_for('users.login') }}>Login page</a>!
    </div>


{% endblock %}